### ISSUE TITLE
Choo 6 release candidate feedback

### ISSUE THREAD

**Issue by yoshuawuyts** [choojs/choo#519]
This is an aggregate issue for feedback on the Choo 6 RC. The release is complete feature-wise, but there might be bugs. Let us know what's going wrong (or going very right) and we'll be happy to help out. Cheers!

## Todos
- [x] remove the default route option from the choo constructor, rely on `'*'` routes instead
- [x] parse querystrings into objects and set as `state.query`
- [x] https://github.com/yoshuawuyts/nanohref/issues/3 - deprecate the `data-no-routing` attribute and check other hosts + `target="noopener"` links instead
- [ ] fix whitespace in `yo-yoify` https://github.com/shama/yo-yoify/issues/49
- [ ] fix whitespace in `pelo` https://github.com/shuhei/pelo/issues/7
- [ ] upgrading bankai to new `yo-yoify`
- [ ] upgrading `bel` to new `pelo` (fixes test failures in choo)

## Known issues
None so far

## See Also
- https://github.com/yoshuawuyts/choo/pull/489

**Comment by yoshuawuyts** [comment]
Ok, maybe a lil more:
- https://github.com/yoshuawuyts/nanorouter/issues/6 - wanted to change the API anyway, and would be semver major anyway. Might as well do it now.
- https://github.com/yoshuawuyts/nanohref/issues/3 - deprecate the `data-no-routing` attribute and check other hosts + `target="_blank"` links instead

**Comment by yoshuawuyts** [comment]
Implemented the link handling here https://github.com/yoshuawuyts/nanohref/pull/6

**Comment by s3ththompson** [comment]
Any chance for out-of-the-box ssr with bankai for 6?

**Comment by yoshuawuyts** [comment]
Already works out of the box! 🎉 although I haven't had time to polish the
implementation haha; patches are def welcome!
https://github.com/yoshuawuyts/choo-reload

**Comment by yoshuawuyts** [comment]
Oh lol, SSR !== server side reload haha. Oops, bit sleepy - yeah, planning
to add that to the next release of bankai; whipped up a patch today, and
just want to add ciritical path CSS inlining too and we should be good to
go :D

**Comment by ungoldman** [comment]
Choo 6 is very released! Ok to close this?

**Comment by yoshuawuyts** [comment]
@ungoldman ah yeah, good one! Feel free to just close issues like these if you spot them :grin:
