### ISSUE TITLE
v7.0.0

### ISSUE THREAD

**Issue by tornqvist** [choojs/choo#700]
We have a few breaking changes queued up for the next major release and I think it's about time to move ahead with those.

- [x] #699 Disable hash routing by default
- [x] #698 Match route before init stores
- [x] #649 Immutable state on SSR (toString)
- [x] #616 Use Object.assign instead of xtend
- [x] #578 more timings
- [x] #701 Update nanorouter 

Related:
- https://github.com/choojs/choo-service-worker/pull/14 Use Object.assign instead of extend
- https://github.com/choojs/nanologger/pull/11 Use Object.assign instead of xtend
- https://github.com/choojs/choo-devtools/pull/34 Update nanologger
- https://github.com/choojs/bankai/pull/527 Update choo

There were discussions in #563 about including asynchronous routes in v7 but the discussion on async routes kind of died off in #653. Also, it could very well be added in a minor later on and is easy enough to implement in user land.

**Comment by tornqvist** [comment]
I take the reactions as approval of the changes. I figured I'll let this sit here for a day or so before going ahead with merging everything so that people who have better things to do during the weekend get a chance to review it.

**Comment by bcomnes** [comment]
I think skipping async until someone really wants to champion that feature is fine.  These changes look needed.  As we spoke via IRC earlier, we should do a beta release before we do a production release on 7.0.0 and make sure everything is working together for a bit before we fully release.

**Comment by ungoldman** [comment]
I second the words of @bcomnes.

**Comment by tornqvist** [comment]
Ohh, I forgot to post here, for those not on IRC.
There's a beta out (`v7.0.0-0`) and here's the change log: https://github.com/choojs/choo/releases/tag/v7.0.0-0

I've been using it for the past week (not in production yet) but it has held up nicely, no issues so far.

**Comment by ungoldman** [comment]
Thanks @tornqvist, change log looks great to me 👍

**Comment by tornqvist** [comment]
:tada: v7.0.0 has now been published!

**Comment by bcomnes** [comment]
Thank you @tornqvist for your hard work on this!
